# Generated by Django 4.2.16 on 2024-12-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_about_me_user_alcoholic_user_caste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alcoholic',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='smoker',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=6, null=True),
        ),
    ]
