# Generated by Django 4.2.16 on 2024-12-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_alcoholic_alter_user_smoker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alcoholic',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='smoker',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=6, null=True),
        ),
    ]
