# Generated by Django 4.2.16 on 2024-12-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_alcoholic_alter_user_smoker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
