# Generated by Django 4.2.16 on 2025-03-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_community_user_custom_id_user_family_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
