# Generated by Django 4.2.16 on 2024-12-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('time_period', models.PositiveIntegerField()),
                ('messages', models.PositiveIntegerField()),
                ('calls', models.PositiveIntegerField()),
            ],
        ),
    ]
