# Generated by Django 4.2.16 on 2024-12-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('message', 'Message'), ('call', 'Call')], max_length=7)),
                ('messages', models.PositiveIntegerField(default=0)),
                ('calls', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
