# Generated by Django 4.2.16 on 2024-12-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
