# Generated by Django 4.2.16 on 2024-12-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_addons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='addons',
        ),
    ]
