# Generated by Django 4.2.16 on 2024-12-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
