# Generated by Django 4.2.16 on 2024-12-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_usersubscription_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='calls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='messages',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
